"""initial migration

Revision ID: 5c7c91f661bf
Revises:
Create Date: 2026-07-03 12:41:42.289029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c7c91f661bf"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "builds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_model", sa.String(), nullable=False),
        sa.Column("lora_config", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "datasets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("train_split", sa.String(), nullable=True),
        sa.Column("val_split", sa.String(), nullable=True),
        sa.Column("eval_split", sa.String(), nullable=True),
        sa.Column("processing_config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("rouge_score", sa.Float(), nullable=True),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("verdict", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("epochs_completed", sa.Integer(), nullable=True),
        sa.Column("loss", sa.Float(), nullable=True),
        sa.Column("gpu_usage", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "serves",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("model_path", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sources")
    op.drop_table("serves")
    op.drop_table("runs")
    op.drop_table("evals")
    op.drop_table("datasets")
    op.drop_table("builds")
    # ### end Alembic commands ###
